//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public int itemNumber { get; set; }
        public string userName { get; set; }
        public string manufacturer { get; set; }
        public string itemType { get; set; }
        public string modelName { get; set; }
        public string status { get; set; }
        public int price { get; set; }
        public string image { get; set; }
        public string C_description { get; set; }
        public int views { get; set; }
    
        public virtual itemType itemType1 { get; set; }
        public virtual manufacturer manufacturer1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
